// examples/vue/src/App.vue
<script setup lang="ts">
import { mountConvexPulseDevtools } from 'convex-pulse/devtools'
import { ConvexPulseVueClientKey } from 'convex-pulse/vue'
import { inject, onMounted, onUnmounted } from 'vue'

const client = inject(ConvexPulseVueClientKey)
if (client === undefined)
  throw new Error('Convex Pulse Vue client was not provided')

let unmountDevtools: () => void = () => undefined
onMounted(() => {
  const devtools = mountConvexPulseDevtools(client, { initialIsOpen: true })
  unmountDevtools = () => devtools.unmount()
})
onUnmounted(() => unmountDevtools())
</script>

<template>
  <div class="app-shell"><RouterView /></div>
</template>

// examples/angular/src/app/app.ts
import { Component, DestroyRef, inject } from '@angular/core'
import { RouterOutlet } from '@angular/router'
import { CONVEX_PULSE_CLIENT } from 'convex-pulse/angular'
import { mountConvexPulseDevtools } from 'convex-pulse/devtools'

@Component({
  imports: [RouterOutlet],
  selector: 'app-root',
  template: '<div class="app-shell"><router-outlet /></div>'
})
export class App {
  constructor() {
    const devtools = mountConvexPulseDevtools(inject(CONVEX_PULSE_CLIENT), {
      initialIsOpen: true
    })
    inject(DestroyRef).onDestroy(() => devtools.unmount())
  }
}
