// examples/react/src/App.tsx
import {
  ConvexPulseDevtools,
  ConvexPulseReactClient,
  ConvexPulseReactProvider,
  useMutation,
  usePrefetchQuery,
  useQuery
} from 'convex-pulse/react'
import { useState } from 'react'
import type { FormEvent } from 'react'
import { Link, Route, Routes, useParams } from 'react-router-dom'

import { api } from '#convex/api'
import type { Id } from '#convex/dataModel'

import './App.css'

const client = new ConvexPulseReactClient(import.meta.env.VITE_CONVEX_URL, {
  gcTime: 60_000
})

export default function App() {
  return (
    <ConvexPulseReactProvider convex={client}>
      <div className="app-shell">
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/tasks/:taskId" element={<Task />} />
        </Routes>
      </div>
      <ConvexPulseDevtools initialIsOpen />
    </ConvexPulseReactProvider>
  )
}

function Home() {
  const [title, setTitle] = useState('')
  const taskList = useQuery(api.tasks.list, { args: {} })
  const prefetchTask = usePrefetchQuery(api.tasks.get)
  const createTask = useMutation(api.tasks.create, {
    optimistic: ({ store, data, optimisticId }) =>
      store.get(api.tasks.list).append({
        _id: optimisticId,
        _creationTime: Date.now(),
        done: false,
        ...data
      })
  })

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()

    const trimmedTitle = title.trim()
    if (!trimmedTitle) return

    void createTask({ title: trimmedTitle })
    setTitle('')
  }

  function prefetch(id: Id<'task'>) {
    void prefetchTask({ id }).ready.catch(() => undefined)
  }

  return (
    <main>
      <header className="hero">
        <p className="eyebrow">Convex Pulse · React</p>
        <h1>Small tasks, visible state.</h1>
        <p className="lede">
          Hover a task to prefetch it, open it to subscribe, then come back to
          watch the inactive query age in the inspector.
        </p>
      </header>

      <section className="task-card" aria-labelledby="tasks-heading">
        <div className="section-heading">
          <div>
            <p className="section-kicker">Cloud data</p>
            <h2 id="tasks-heading">Tasks</h2>
          </div>
          {taskList.status === 'success' && (
            <span className="task-count">{taskList.data.length}</span>
          )}
        </div>

        <form onSubmit={handleSubmit}>
          <input
            aria-label="Task title"
            onChange={(event) => setTitle(event.target.value)}
            placeholder="What needs doing?"
            value={title}
          />
          <button type="submit">Add task</button>
        </form>

        {taskList.status === 'pending' && <p className="state">Loading…</p>}
        {taskList.status === 'error' && (
          <p className="state error" role="alert">
            {taskList.error.message}
          </p>
        )}
        {taskList.status === 'success' && taskList.data.length === 0 && (
          <p className="state">No tasks yet. Add the first one.</p>
        )}
        {taskList.status === 'success' && taskList.data.length > 0 && (
          <ul className="task-list">
            {taskList.data.map((task) => (
              <li key={task._id}>
                <Link
                  to={`/tasks/${task._id}`}
                  onFocus={() => prefetch(task._id)}
                  onMouseEnter={() => prefetch(task._id)}
                >
                  <span className={task.done ? 'done' : undefined}>
                    {task.title}
                  </span>
                  <span aria-hidden="true">↗</span>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </section>
    </main>
  )
}

function Task() {
  const { taskId } = useParams<{ taskId: string }>()
  const task = useQuery(api.tasks.get, {
    args: { id: taskId as Id<'task'> }
  })
  const setDone = useMutation(api.tasks.setDone, {
    optimistic: ({ data, store }) =>
      store.get(api.tasks.get, { id: data.id }).merge({ done: data.done })
  })

  return (
    <main>
      <Link className="back-link" to="/">
        ← All tasks
      </Link>
      <article className="detail-card">
        <p className="eyebrow">Individual query</p>
        {task.status === 'pending' && <p className="state">Loading task…</p>}
        {task.status === 'error' && (
          <p className="state error" role="alert">
            {task.error.message}
          </p>
        )}
        {task.status === 'success' && (
          <>
            <h1>{task.data.title}</h1>
            <label className="completion-control">
              <input
                checked={task.data.done ?? false}
                type="checkbox"
                onChange={(event) =>
                  void setDone({
                    done: event.target.checked,
                    id: task.data._id
                  })
                }
              />
              <span>
                <strong>{task.data.done ? 'Completed' : 'Open'}</strong>
                <small>Synced live through Convex</small>
              </span>
            </label>
            <dl>
              <div>
                <dt>Document ID</dt>
                <dd>{task.data._id}</dd>
              </div>
              <div>
                <dt>Created</dt>
                <dd>{new Date(task.data._creationTime).toLocaleString()}</dd>
              </div>
            </dl>
          </>
        )}
      </article>
    </main>
  )
}

// examples/solid/src/App.tsx
import { A, Route, Router, useParams } from '@solidjs/router'
import { mountConvexPulseDevtools } from 'convex-pulse/devtools'
import {
  ConvexPulseSolidClient,
  createMutation,
  createPrefetchQuery,
  createQuery
} from 'convex-pulse/solid'
import { createSignal, For, onMount, Show } from 'solid-js'

import { api } from '#convex/api'
import type { Id } from '#convex/dataModel'

import './App.css'

const client = new ConvexPulseSolidClient(import.meta.env.VITE_CONVEX_URL, {
  gcTime: 60_000
})

export default function App() {
  onMount(() => {
    const devtools = mountConvexPulseDevtools(client, { initialIsOpen: true })
    return () => devtools.unmount()
  })

  return (
    <Router root={(props) => <div class="app-shell">{props.children}</div>}>
      <Route path="/" component={Home} />
      <Route path="/tasks/:taskId" component={Task} />
    </Router>
  )
}

function Home() {
  const [title, setTitle] = createSignal('')
  const taskList = createQuery(client, api.tasks.list, { args: {} })
  const prefetchTask = createPrefetchQuery(client, api.tasks.get)
  const createTask = createMutation(client, api.tasks.create, {
    optimistic: ({ store, data, optimisticId }) =>
      store.get(api.tasks.list).append({
        _id: optimisticId,
        _creationTime: Date.now(),
        done: false,
        ...data
      })
  })

  function handleSubmit(event: SubmitEvent) {
    event.preventDefault()
    const trimmedTitle = title().trim()
    if (!trimmedTitle) return
    void createTask({ title: trimmedTitle })
    setTitle('')
  }

  function prefetch(id: Id<'task'>) {
    void prefetchTask({ id }).ready.catch(() => undefined)
  }

  return (
    <main>
      <header class="hero">
        <p class="eyebrow">Convex Pulse · Solid</p>
        <h1>Small tasks, visible state.</h1>
        <p class="lede">
          Hover a task to prefetch it, open it to subscribe, then come back to
          watch the inactive query age in the inspector.
        </p>
      </header>
      <section class="task-card" aria-labelledby="tasks-heading">
        <div class="section-heading">
          <div>
            <p class="section-kicker">Cloud data</p>
            <h2 id="tasks-heading">Tasks</h2>
          </div>
          <Show when={taskList().status === 'success'}>
            <span class="task-count">{taskList().data?.length}</span>
          </Show>
        </div>
        <form onSubmit={handleSubmit}>
          <input
            aria-label="Task title"
            onInput={(event) => setTitle(event.currentTarget.value)}
            placeholder="What needs doing?"
            value={title()}
          />
          <button type="submit">Add task</button>
        </form>
        <Show when={taskList().status === 'pending'}>
          <p class="state">Loading…</p>
        </Show>
        <Show when={taskList().status === 'error'}>
          <p class="state error" role="alert">
            {taskList().error?.message}
          </p>
        </Show>
        <Show
          when={
            taskList().status === 'success' && taskList().data?.length === 0
          }
        >
          <p class="state">No tasks yet. Add the first one.</p>
        </Show>
        <Show
          when={
            taskList().status === 'success' &&
            (taskList().data?.length ?? 0) > 0
          }
        >
          <ul class="task-list">
            <For each={taskList().data}>
              {(task) => (
                <li>
                  <A
                    href={`/tasks/${task._id}`}
                    onFocus={() => prefetch(task._id)}
                    onMouseEnter={() => prefetch(task._id)}
                  >
                    <span classList={{ done: task.done }}>{task.title}</span>
                    <span aria-hidden="true">↗</span>
                  </A>
                </li>
              )}
            </For>
          </ul>
        </Show>
      </section>
    </main>
  )
}

function Task() {
  const params = useParams<{ taskId: string }>()
  const task = createQuery(client, api.tasks.get, {
    args: { id: params.taskId as Id<'task'> }
  })
  const setDone = createMutation(client, api.tasks.setDone, {
    optimistic: ({ data, store }) =>
      store.get(api.tasks.get, { id: data.id }).merge({ done: data.done })
  })

  return (
    <main>
      <A class="back-link" href="/">
        ← All tasks
      </A>
      <article class="detail-card">
        <p class="eyebrow">Individual query</p>
        <Show when={task().status === 'pending'}>
          <p class="state">Loading task…</p>
        </Show>
        <Show when={task().status === 'error'}>
          <p class="state error" role="alert">
            {task().error?.message}
          </p>
        </Show>
        <Show when={task().status === 'success' && task().data}>
          {(value) => (
            <>
              <h1>{value().title}</h1>
              <label class="completion-control">
                <input
                  checked={value().done ?? false}
                  type="checkbox"
                  onChange={(event) =>
                    void setDone({
                      done: event.currentTarget.checked,
                      id: value()._id
                    })
                  }
                />
                <span>
                  <strong>{value().done ? 'Completed' : 'Open'}</strong>
                  <small>Synced live through Convex</small>
                </span>
              </label>
              <dl>
                <div>
                  <dt>Document ID</dt>
                  <dd>{value()._id}</dd>
                </div>
                <div>
                  <dt>Created</dt>
                  <dd>{new Date(value()._creationTime).toLocaleString()}</dd>
                </div>
              </dl>
            </>
          )}
        </Show>
      </article>
    </main>
  )
}
