// examples/sveltekit/src/routes/+page.svelte
<script lang="ts">
  import { useMutation } from 'convex-pulse/svelte'
  import type { PageProps } from './$types'

  import { api } from '#convex/api'

  let { data }: PageProps = $props()
  let title = $state('')
  let hydrated = $state(false)
  const tasks = $derived(data.tasks)
  const labels = $derived(data.labels)
  const createTask = useMutation(api.tasks.create)
  const removeTask = useMutation(api.tasks.remove)

  $effect(() => {
    hydrated = true
  })

  function handleSubmit(event: SubmitEvent) {
    event.preventDefault()
    const trimmedTitle = title.trim()
    if (trimmedTitle.length === 0) return

    void createTask({ title: trimmedTitle })
    title = ''
  }
</script>

<main>
  <h1>Convex Pulse · SvelteKit</h1>
  <p>Hydrated: {hydrated ? 'yes' : 'no'}</p>
  <p>Skipped: {data.skipped.status}</p>
  <p>Labels: {labels.data?.join(', ')}</p>
  {#if labels.canLoadMore}
    <button type="button" onclick={() => labels.loadMore(3)}>Load more labels</button>
  {/if}
  <form onsubmit={handleSubmit}>
    <input aria-label="Task title" placeholder="What needs doing?" bind:value={title} />
    <button type="submit">Add task</button>
  </form>
  {#if $createTask.status === 'error'}
    <p role="alert">{$createTask.error.message}</p>
  {/if}
  {#if tasks.status === 'pending'}
    <p>Loading…</p>
  {:else if tasks.status === 'error'}
    <p role="alert">{tasks.error.message}</p>
  {:else if tasks.data?.length === 0}
    <p>No tasks yet.</p>
  {:else}
    <ul>
      {#each tasks.data ?? [] as task (task._id)}
        <li>
          {task.title}
          <button type="button" onclick={() => void removeTask({ id: task._id })}>
            Delete {task.title}
          </button>
        </li>
      {/each}
    </ul>
  {/if}
</main>

// examples/tanstack-start/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router'
import { createServerFn } from '@tanstack/react-start'
import { ConvexPulseHttpClient } from 'convex-pulse/http'
import { useMutation, usePreloadedQuery } from 'convex-pulse/react'
import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'

import { api } from '#convex/api'

const loadTasks = createServerFn({ method: 'GET' }).handler(() => {
  const client = new ConvexPulseHttpClient(
    requiredEnvironmentVariable('VITE_CONVEX_URL', process.env.VITE_CONVEX_URL)
  )
  return client.preloadQuery(api.tasks.list, { args: {} })
})
export const Route = createFileRoute('/')({
  component: Home,
  loader: () => loadTasks()
})

function Home() {
  const preloadedTasks = Route.useLoaderData()

  return <TaskList preloadedTasks={preloadedTasks} />
}

function TaskList({ preloadedTasks }: TaskListProps) {
  const [title, setTitle] = useState('')
  const [hydrated, setHydrated] = useState(false)
  const tasks = usePreloadedQuery(preloadedTasks)
  const createTask = useMutation(api.tasks.create)
  const removeTask = useMutation(api.tasks.remove)

  useEffect(() => setHydrated(true), [])

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const trimmedTitle = title.trim()
    if (trimmedTitle.length === 0) return

    void createTask({ title: trimmedTitle })
    setTitle('')
  }

  return (
    <main>
      <h1>Convex Pulse · TanStack Start</h1>
      <p>Hydrated: {hydrated ? 'yes' : 'no'}</p>
      <form onSubmit={handleSubmit}>
        <input
          aria-label="Task title"
          onChange={(event) => setTitle(event.target.value)}
          placeholder="What needs doing?"
          value={title}
        />
        <button type="submit">Add task</button>
      </form>
      {createTask.error === null ? null : (
        <p role="alert">{createTask.error.message}</p>
      )}
      {tasks.length === 0 ? (
        <p>No tasks yet.</p>
      ) : (
        <ul>
          {tasks.map((task) => (
            <li key={task._id}>
              {task.title}{' '}
              <button
                type="button"
                onClick={() => void removeTask({ id: task._id })}
              >
                Delete {task.title}
              </button>
            </li>
          ))}
        </ul>
      )}
    </main>
  )
}

function requiredEnvironmentVariable(name: string, value: string | undefined) {
  if (value === undefined) {
    throw new Error(`${name} is not set`)
  }
  return value
}

type TaskListProps = Readonly<{
  preloadedTasks: Awaited<ReturnType<typeof loadTasks>>
}>
